name: Build and publish a Docker image to ghcr.io
on:

  # publish on pushes to the main branch (image tagged as "latest")
  # image name: will be: ghcr.io/${{ github.repository }}:latest
  # e.g.: ghcr.io/intersystems-community/intersystems-iris-dev-template:latest
  push:
    branches:
      - master

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # optionally push to the Docker Hub (docker.io)
          # docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}  # see https://hub.docker.com/settings/security
